### ISSUE TITLE
CountDownController needs to report current status

### ISSUE THREAD

**Issue by Ro-El** [MuhammadUsamaSiddiqui/circular_countdown_timer#21]
Need to be able to get CountDownController.isAnimating  (isPaused etc.) or something similar to be able to build adaptive widgets that change based on animation status.

Something similar could also be achieved by setting a variable like timerRunning on start, but this package also doesn't allow you to setState in onStart. It also doesn't allow you to do controller.start() in initState.

These limitations seem fairly severe.

**Comment by MuhammadUsamaSiddiqui** [comment]
1) Added parameters (isStarted, isPaused, isResumed) in CountDownController to get the current status of Countdown Timer.

2) You don't need to call `controller.start()` in ` initState` because `CircularCountDownTimer` has a parameter `autoStart` to handle timer start.

3) You can do `setState` in `onStart` method like this:

```
onStart: () {
  WidgetsBinding.instance.addPostFrameCallback((_) {
    setState(() {
      debugPrint('Countdown Started');
    });
  });
}
```
