### ISSUE TITLE
Feature Request: Access Current Time While Timer Running

### ISSUE THREAD

**Issue by Rhino773** [MuhammadUsamaSiddiqui/circular_countdown_timer#9]
Hello, 
I love what you have done with this circular countdown timer, but just wanted to make more of a feature request than an issue. I was wondering if I can take the exact time in the middle of the timer? An example of this is when I move to another screen but I would like to take the exact time left/used in the timer to the next screen by setting the current time to a variable. I would love if this could be implemented into the package! 

Thanks,
Rhino773 :)

**Comment by MuhammadUsamaSiddiqui** [comment]
Hi! Thanks for your Kind words.

I have added `getTime` method in **CountDownController** to get Current Time (i.e Time Used in terms of **Forward Countdown** and Time Left in terms of **Reverse Countdown**) of Countdown Timer.

If Hour in current time is not equal to zero then `getTime` method return String in **HH:mm:ss** format, otherwise in "mm:ss" format.

**Comment by Rhino773** [comment]
Thank you! This is a great addition to the package! Keep up the great work!
